### ISSUE TITLE
On fresh install, unable to enable due to NoClassDefFoundError.

### ISSUE THREAD

**Issue by alliraine** [pop4959/Stress#2]
Fresh install of Paper Version 1.16.3 Build# 207 I get this error.

>.... [15:23:17 ERROR]: Error occurred while enabling Stress v1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/luckperms/api/context/ContextCalculator
at org.popcraft.stress.Stress.onEnable(Stress.java:79) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-207]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.context.ContextCalculator
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-207]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
... 11 more
>.... [15:23:17 INFO]: [Stress] Disabling Stress v1.0.2
>.... [15:23:17 ERROR]: Error occurred while disabling Stress v1.0.2 (Is it up to date?)
java.lang.NoClassDefFoundError: net/luckperms/api/context/ContextCalculator
at org.popcraft.stress.Stress.onDisable(Stress.java:86) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.3.jar:git-Paper-207]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-207]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassNotFoundException: net.luckperms.api.context.ContextCalculator
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_262]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.16.3.jar:git-Paper-207]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.16.3.jar:git-Paper-207]
at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_262]
at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_262]
... 13 more

**Comment by pop4959** [comment]
Is the LuckPerms plugin installed on your server? I think I might know what is causing this. Try installing version 1.0.1 for now, since that is the same but without LuckPerms integration.

**Comment by alliraine** [comment]
Yup! I don't have luck perms and rolling back worked. :)

**Comment by pop4959** [comment]
Thanks for letting me know, I'll try to put a release out soon that fixes this issue for people who don't have LuckPerms installed. You don't need to take any further action though, as this update won't have any other impact for you in comparison to 1.0.1.
